project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!/slides"
  - "!/handouts"
  - "activities.qmd"
  - "!/assignmentment_data/IA2_template.qmd"
  resources:
    - "CNAME"

website:
  title: "ETF3231/ETF5231 Business Forecasting"
  site-url: "https://bf.numbat.space/"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Schedule
        icon: calendar2-fill
        menu:
          - week1/index.qmd
          - week2/index.qmd
          - week3/index.qmd
          - week4/index.qmd
          - week5/index.qmd
          - week6/index.qmd
          - week7/index.qmd
          - week8/index.qmd
          - week9/index.qmd
          - week10/index.qmd
          - week11/index.qmd
          - week12/index.qmd
      - text: Discussion
        icon: chat-fill
        href: https://edstem.org/au/courses/21006
      - text: Moodle
        icon: mortarboard-fill
        href: https://learning.monash.edu/course/view.php?id=26702
      - text: Textbook
        icon: book
        href: https://OTexts.com/fpp3
      - text: R Playground
        icon: terminal-fill
        href: playground/index.qmd

date-format: "D MMMM YYYY"

freeze: auto

format:
  html:
    theme: [cosmo, numbat.scss]
    highlight: textmate
    toc: true
    mainfont: "Fira Sans"
    html-math-method: katex
    include-in-header:
      file: header.html

execute:
  echo: false
  message: false
  warning: false
  cache: false
